from pathlib import Path
import re

path = Path('data/default/professions/engineering.lua')
text = path.read_text()
if 'version = 10,' not in text:
    raise SystemExit('Expected Engineering version 10')
items = text.split('items = {', 1)[1].split('recipes = {', 1)[0]
if 'name = "Solid Dynamite"' in items:
    raise SystemExit('150-225 item slice already present')

block = r'''            {
                bindingFlag = "none",
                canDisenchant = false,
                canSell = true,
                canStack = true,
                canTrade = true,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 175,
                        showOnTooltip = true,
                        skillRef = "f82db71a:xprqs3y1",
                        tooltipTextOverride = "",
                        type = "skill_requirement",
                    },
                },
                description = "",
                icon = "interface/icons/inv_misc_bomb_06.blp",
                id = "u803vxvo",
                itemLevel = 35,
                itemType = "consumable",
                maxStackSize = 20,
                name = "Solid Dynamite",
                quality = "common",
                stats = {},
                tags = {},
                useSpellRef = "af503002:c218fe29",
            },
            {
                bindingFlag = "none",
                canDisenchant = false,
                canSell = true,
                canStack = true,
                canTrade = true,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 175,
                        showOnTooltip = true,
                        skillRef = "f82db71a:xprqs3y1",
                        tooltipTextOverride = "",
                        type = "skill_requirement",
                    },
                },
                description = "",
                icon = "interface/icons/inv_misc_bomb_08.blp",
                id = "ao0kju8m",
                itemLevel = 35,
                itemType = "consumable",
                maxStackSize = 10,
                name = "Iron Grenade",
                quality = "common",
                stats = {},
                tags = {},
                useSpellRef = "af503002:c43f2b9e",
            },
            {
                armorWeight = "cloth",
                bindingFlag = "bind_on_equip",
                canDisenchant = true,
                canSell = true,
                canStack = false,
                canTrade = true,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 175,
                        showOnTooltip = true,
                        skillRef = "f82db71a:xprqs3y1",
                        tooltipTextOverride = "",
                        type = "skill_requirement",
                    },
                },
                description = "",
                icon = "interface/icons/inv_helmet_47.blp",
                id = "u6ib71ea",
                itemLevel = 35,
                itemType = "armor",
                maxGenericModificationCounts = { mod = 1 },
                maxModificationCounts = { mod = 1 },
                maxStackSize = 1,
                name = "Bright-Eye Goggles",
                quality = "uncommon",
                stats = {
                    { sourceStatRef = "f82db71a:v42albuv", value = 38 },
                    { sourceStatRef = "f82db71a:ygjno50i", value = 9 },
                    { sourceStatRef = "f82db71a:kec9rhli", value = 9 },
                },
                tags = {},
                validSlotRefs = { "f82db71a:bgvs1zx6" },
            },
            {
                armorWeight = "cloth",
                bindingFlag = "bind_on_equip",
                canDisenchant = true,
                canSell = true,
                canStack = false,
                canTrade = true,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 32,
                        showOnTooltip = true,
                        tooltipTextOverride = "",
                        type = "level",
                    },
                    {
                        invert = false,
                        minimumValue = 185,
                        showOnTooltip = true,
                        skillRef = "f82db71a:xprqs3y1",
                        tooltipTextOverride = "",
                        type = "skill_requirement",
                    },
                },
                description = "",
                icon = "interface/icons/inv_helmet_44.blp",
                id = "sy21st9n",
                itemLevel = 37,
                itemType = "armor",
                maxGenericModificationCounts = { mod = 1 },
                maxModificationCounts = { mod = 1 },
                maxStackSize = 1,
                name = "Craftsman's Monocle",
                quality = "uncommon",
                stats = {
                    { sourceStatRef = "f82db71a:v42albuv", value = 40 },
                    { sourceStatRef = "f82db71a:75y3a8ib", value = 15 },
                },
                tags = {},
                validSlotRefs = { "f82db71a:bgvs1zx6" },
            },
            {
                bindingFlag = "none",
                canDisenchant = false,
                canSell = true,
                canStack = true,
                canTrade = true,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 27,
                        showOnTooltip = true,
                        tooltipTextOverride = "",
                        type = "level",
                    },
                },
                description = "",
                icon = "interface/icons/inv_misc_bomb_04.blp",
                id = "ossr5jtb",
                itemLevel = 37,
                itemType = "consumable",
                maxStackSize = 5,
                name = "Flash Bomb",
                quality = "common",
                stats = {},
                tags = {},
            },
            {
                bindingFlag = "none",
                canDisenchant = false,
                canSell = true,
                canStack = true,
                canTrade = true,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 190,
                        showOnTooltip = true,
                        skillRef = "f82db71a:xprqs3y1",
                        tooltipTextOverride = "",
                        type = "skill_requirement",
                    },
                },
                description = "",
                icon = "interface/icons/inv_misc_bomb_01.blp",
                id = "j4k4yrbd",
                itemLevel = 43,
                itemType = "consumable",
                maxStackSize = 10,
                name = "Big Iron Bomb",
                quality = "common",
                stats = {},
                tags = {},
                useSpellRef = "af503002:4789bef4",
            },
            {
                bindingFlag = "none",
                canDisenchant = false,
                canSell = true,
                canStack = true,
                canTrade = true,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 30,
                        showOnTooltip = true,
                        tooltipTextOverride = "",
                        type = "level",
                    },
                },
                description = "",
                icon = "interface/icons/inv_misc_bomb_03.blp",
                id = "4bf7dayn",
                itemLevel = 40,
                itemType = "consumable",
                maxStackSize = 20,
                name = "EZ-Thro Dynamite II",
                quality = "common",
                stats = {},
                tags = {},
                useSpellRef = "af503002:b4fdbc86",
            },
            {
                armorWeight = "cloth",
                bindingFlag = "bind_on_equip",
                canDisenchant = true,
                canSell = true,
                canStack = false,
                canTrade = true,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 205,
                        showOnTooltip = true,
                        skillRef = "f82db71a:xprqs3y1",
                        tooltipTextOverride = "",
                        type = "skill_requirement",
                    },
                },
                description = "",
                icon = "interface/icons/inv_helmet_47.blp",
                id = "nc4249yo",
                itemLevel = 41,
                itemType = "armor",
                maxGenericModificationCounts = { mod = 1 },
                maxModificationCounts = { mod = 1 },
                maxStackSize = 1,
                name = "Fire Goggles",
                quality = "uncommon",
                stats = {
                    { sourceStatRef = "f82db71a:v42albuv", value = 44 },
                    { sourceStatRef = "f82db71a:0w7c7p09", value = 17 },
                },
                tags = {},
                validSlotRefs = { "f82db71a:bgvs1zx6" },
            },
            {
                armorWeight = "cloth",
                bindingFlag = "bind_on_pickup",
                canDisenchant = true,
                canSell = true,
                canStack = false,
                canTrade = false,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 205,
                        showOnTooltip = true,
                        skillRef = "f82db71a:xprqs3y1",
                        tooltipTextOverride = "",
                        type = "skill_requirement",
                    },
                },
                description = "",
                icon = "interface/icons/inv_helmet_60.blp",
                id = "ayt4p1l0",
                itemLevel = 41,
                itemType = "armor",
                maxGenericModificationCounts = { mod = 1 },
                maxModificationCounts = { mod = 1 },
                maxStackSize = 1,
                name = "Goblin Construction Helmet",
                quality = "uncommon",
                stats = {
                    { sourceStatRef = "f82db71a:v42albuv", value = 44 },
                    { sourceStatRef = "f82db71a:0w7c7p09", value = 15 },
                },
                tags = {},
                validSlotRefs = { "f82db71a:bgvs1zx6" },
            },
            {
                armorWeight = "mail",
                bindingFlag = "bind_on_pickup",
                canDisenchant = true,
                canSell = true,
                canStack = false,
                canTrade = false,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 205,
                        showOnTooltip = true,
                        skillRef = "f82db71a:xprqs3y1",
                        tooltipTextOverride = "",
                        type = "skill_requirement",
                    },
                },
                description = "",
                icon = "interface/icons/inv_helmet_25.blp",
                id = "yv5axgoy",
                itemLevel = 41,
                itemType = "armor",
                maxGenericModificationCounts = { mod = 1 },
                maxModificationCounts = { mod = 1 },
                maxStackSize = 1,
                name = "Goblin Mining Helmet",
                quality = "uncommon",
                stats = {
                    { sourceStatRef = "f82db71a:v42albuv", value = 190 },
                    { sourceStatRef = "f82db71a:ygjno50i", value = 15 },
                },
                tags = {},
                validSlotRefs = { "f82db71a:bgvs1zx6" },
            },
            {
                bindingFlag = "bind_on_equip",
                canDisenchant = true,
                canSell = true,
                canStack = false,
                canTrade = true,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 36,
                        showOnTooltip = true,
                        tooltipTextOverride = "",
                        type = "level",
                    },
                },
                damageMode = "range",
                damageSchoolRef = "f82db71a:v1azo4j6",
                description = "",
                icon = "interface/icons/inv_weapon_rifle_07.blp",
                id = "kq3v7ivg",
                isTwoHanded = false,
                itemLevel = 41,
                itemType = "weapon",
                maxDamagePerTurn = 68,
                maxGenericModificationCounts = { mod = 1 },
                maxModificationCounts = { mod = 1 },
                maxStackSize = 1,
                minDamagePerTurn = 36,
                name = "Mithril Blunderbuss",
                quality = "uncommon",
                stats = {
                    { sourceStatRef = "f82db71a:xqz0daz2", value = 5 },
                },
                tags = {},
                validSlotRefs = { "f82db71a:q8ve6n6t" },
                weaponTypeRef = "f82db71a:anoo8qfp",
            },
            {
                armorWeight = "cloth",
                bindingFlag = "bind_on_pickup",
                canDisenchant = true,
                canSell = true,
                canStack = false,
                canTrade = false,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 210,
                        showOnTooltip = true,
                        skillRef = "f82db71a:xprqs3y1",
                        tooltipTextOverride = "",
                        type = "skill_requirement",
                    },
                },
                description = "",
                icon = "interface/icons/inv_helmet_47.blp",
                id = "ld6rvfka",
                itemLevel = 42,
                itemType = "armor",
                maxGenericModificationCounts = { mod = 1 },
                maxModificationCounts = { mod = 1 },
                maxStackSize = 1,
                name = "Gnomish Goggles",
                quality = "uncommon",
                stats = {
                    { sourceStatRef = "f82db71a:v42albuv", value = 45 },
                    { sourceStatRef = "f82db71a:xqz0daz2", value = 9 },
                    { sourceStatRef = "f82db71a:ygjno50i", value = 9 },
                    { sourceStatRef = "f82db71a:kec9rhli", value = 9 },
                },
                tags = {},
                validSlotRefs = { "f82db71a:bgvs1zx6" },
            },
            {
                armorWeight = "cosmetic",
                bindingFlag = "none",
                canDisenchant = false,
                canSell = true,
                canStack = true,
                canTrade = true,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 37,
                        showOnTooltip = true,
                        tooltipTextOverride = "",
                        type = "level",
                    },
                },
                description = "",
                icon = "interface/icons/inv_ammo_bullet_01.blp",
                id = "p9omk6ay",
                itemLevel = 42,
                itemType = "armor",
                maxStackSize = 200,
                name = "Hi-Impact Mithril Slugs",
                quality = "common",
                stats = {
                    { sourceStatRef = "f82db71a:v2rs9cpy", value = 12.5 },
                },
                tags = { "ammo", "bullet" },
                validSlotRefs = { "f82db71a:atsoi5vr" },
            },
            {
                bindingFlag = "none",
                canDisenchant = false,
                canSell = true,
                canStack = true,
                canTrade = true,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 205,
                        showOnTooltip = true,
                        skillRef = "f82db71a:xprqs3y1",
                        tooltipTextOverride = "",
                        type = "skill_requirement",
                    },
                },
                description = "",
                icon = "interface/icons/inv_misc_bomb_02.blp",
                id = "dhwnzvq1",
                itemLevel = 43,
                itemType = "consumable",
                maxStackSize = 10,
                name = "Mithril Frag Bomb",
                quality = "common",
                stats = {},
                tags = {},
                useSpellRef = "af503002:6706cb33",
            },
            {
                armorWeight = "leather",
                bindingFlag = "bind_on_equip",
                canDisenchant = true,
                canSell = true,
                canStack = false,
                canTrade = true,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 215,
                        showOnTooltip = true,
                        skillRef = "f82db71a:xprqs3y1",
                        tooltipTextOverride = "",
                        type = "skill_requirement",
                    },
                },
                description = "",
                icon = "interface/icons/inv_belt_06.blp",
                id = "ubwviy1k",
                itemLevel = 43,
                itemType = "armor",
                maxGenericModificationCounts = { mod = 1 },
                maxModificationCounts = { mod = 1 },
                maxStackSize = 1,
                name = "Gnomish Harm Prevention Belt",
                quality = "uncommon",
                stats = {
                    { sourceStatRef = "f82db71a:v42albuv", value = 66 },
                    { sourceStatRef = "f82db71a:ygjno50i", value = 6 },
                },
                tags = {},
                validSlotRefs = { "f82db71a:haks0gz4" },
            },
            {
                armorWeight = "cloth",
                bindingFlag = "bind_on_equip",
                canDisenchant = true,
                canSell = true,
                canStack = false,
                canTrade = true,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 220,
                        showOnTooltip = true,
                        skillRef = "f82db71a:xprqs3y1",
                        tooltipTextOverride = "",
                        type = "skill_requirement",
                    },
                },
                description = "",
                icon = "interface/icons/inv_helmet_47.blp",
                id = "ztgngwif",
                itemLevel = 44,
                itemType = "armor",
                maxGenericModificationCounts = { mod = 1 },
                maxModificationCounts = { mod = 1 },
                maxStackSize = 1,
                name = "Catseye Ultra Goggles",
                quality = "uncommon",
                stats = {
                    { sourceStatRef = "f82db71a:v42albuv", value = 47 },
                },
                tags = {},
                validSlotRefs = { "f82db71a:bgvs1zx6" },
            },
            {
                bindingFlag = "bind_on_equip",
                canDisenchant = true,
                canSell = true,
                canStack = false,
                canTrade = true,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 39,
                        showOnTooltip = true,
                        tooltipTextOverride = "",
                        type = "level",
                    },
                },
                damageMode = "range",
                damageSchoolRef = "f82db71a:v1azo4j6",
                description = "",
                icon = "interface/icons/inv_weapon_rifle_07.blp",
                id = "m4arujey",
                isTwoHanded = false,
                itemLevel = 44,
                itemType = "weapon",
                maxDamagePerTurn = 76,
                maxGenericModificationCounts = { mod = 1 },
                maxModificationCounts = { mod = 1 },
                maxStackSize = 1,
                minDamagePerTurn = 41,
                name = "Mithril Heavy-bore Rifle",
                quality = "uncommon",
                stats = {
                    { sourceStatRef = "f82db71a:v2rs9cpy", value = 14 },
                },
                tags = {},
                validSlotRefs = { "f82db71a:q8ve6n6t" },
                weaponTypeRef = "f82db71a:anoo8qfp",
            },
            {
                armorWeight = "cloth",
                bindingFlag = "bind_on_equip",
                canDisenchant = true,
                canSell = true,
                canStack = false,
                canTrade = true,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 225,
                        showOnTooltip = true,
                        skillRef = "f82db71a:xprqs3y1",
                        tooltipTextOverride = "",
                        type = "skill_requirement",
                    },
                },
                description = "",
                icon = "interface/icons/inv_boots_02.blp",
                id = "p57fkbo9",
                itemLevel = 45,
                itemType = "armor",
                maxGenericModificationCounts = { mod = 1 },
                maxModificationCounts = { mod = 1 },
                maxStackSize = 1,
                name = "Gnomish Rocket Boots",
                quality = "uncommon",
                stats = {
                    { sourceStatRef = "f82db71a:v42albuv", value = 41 },
                },
                tags = {},
                validSlotRefs = { "f82db71a:raiu9t05" },
            },
            {
                armorWeight = "cloth",
                bindingFlag = "bind_on_equip",
                canDisenchant = true,
                canSell = true,
                canStack = false,
                canTrade = true,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 225,
                        showOnTooltip = true,
                        skillRef = "f82db71a:xprqs3y1",
                        tooltipTextOverride = "",
                        type = "skill_requirement",
                    },
                },
                description = "",
                icon = "interface/icons/inv_gizmo_rocketboot_01.blp",
                id = "wwp0afe8",
                itemLevel = 45,
                itemType = "armor",
                maxGenericModificationCounts = { mod = 1 },
                maxModificationCounts = { mod = 1 },
                maxStackSize = 1,
                name = "Goblin Rocket Boots",
                quality = "uncommon",
                stats = {
                    { sourceStatRef = "f82db71a:v42albuv", value = 41 },
                },
                tags = {},
                validSlotRefs = { "f82db71a:raiu9t05" },
            },
            {
                armorWeight = "cloth",
                bindingFlag = "bind_on_equip",
                canDisenchant = true,
                canSell = true,
                canStack = false,
                canTrade = true,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 225,
                        showOnTooltip = true,
                        skillRef = "f82db71a:xprqs3y1",
                        tooltipTextOverride = "",
                        type = "skill_requirement",
                    },
                },
                description = "",
                icon = "interface/icons/inv_misc_cape_11.blp",
                id = "v0frozut",
                itemLevel = 45,
                itemType = "armor",
                maxGenericModificationCounts = { mod = 1 },
                maxModificationCounts = { mod = 1 },
                maxStackSize = 1,
                name = "Parachute Cloak",
                quality = "uncommon",
                stats = {
                    { sourceStatRef = "f82db71a:v42albuv", value = 30 },
                    { sourceStatRef = "f82db71a:xqz0daz2", value = 8 },
                },
                tags = {},
                validSlotRefs = { "f82db71a:bqwhrw0g" },
            },
            {
                armorWeight = "cloth",
                bindingFlag = "bind_on_equip",
                canDisenchant = true,
                canSell = true,
                canStack = false,
                canTrade = true,
                conditions = {
                    {
                        invert = false,
                        minimumValue = 215,
                        showOnTooltip = true,
                        skillRef = "f82db71a:xprqs3y1",
                        tooltipTextOverride = "",
                        type = "skill_requirement",
                    },
                },
                description = "",
                icon = "interface/icons/inv_helmet_47.blp",
                id = "asa369xo",
                itemLevel = 43,
                itemType = "armor",
                maxGenericModificationCounts = { mod = 1 },
                maxModificationCounts = { mod = 1 },
                maxStackSize = 1,
                name = "Spellpower Goggles Xtreme",
                quality = "uncommon",
                stats = {
                    { sourceStatRef = "f82db71a:v42albuv", value = 46 },
                    { sourceStatRef = "f82db71a:7t7xgzcx", value = 21 },
                },
                tags = {},
                validSlotRefs = { "f82db71a:bgvs1zx6" },
            },
'''

anchor = '        },\n        recipes = {'
if text.count(anchor) != 1:
    raise SystemExit(f'Unexpected item/recipe anchor count: {text.count(anchor)}')
text = text.replace('    version = 10,', '    version = 11,', 1)
text = text.replace(anchor, block + anchor, 1)
path.write_text(text)

# deterministic structural validation
text = path.read_text()
items = text.split('items = {', 1)[1].split('recipes = {', 1)[0]
expected = [
    'Solid Dynamite','Iron Grenade','Bright-Eye Goggles',"Craftsman's Monocle",'Flash Bomb','Big Iron Bomb',
    'EZ-Thro Dynamite II','Fire Goggles','Goblin Construction Helmet','Goblin Mining Helmet','Mithril Blunderbuss',
    'Gnomish Goggles','Hi-Impact Mithril Slugs','Mithril Frag Bomb','Gnomish Harm Prevention Belt','Catseye Ultra Goggles',
    'Mithril Heavy-bore Rifle','Gnomish Rocket Boots','Goblin Rocket Boots','Parachute Cloak','Spellpower Goggles Xtreme'
]
for name in expected:
    if items.count(f'name = "{name}"') != 1:
        raise SystemExit(f'Bad item count for {name}')
if 'version = 11,' not in text[:200]:
    raise SystemExit('Version was not updated to 11')
for ref in ['af503002:c218fe29','af503002:c43f2b9e','af503002:4789bef4','af503002:b4fdbc86','af503002:6706cb33']:
    if items.count(ref) != 1:
        raise SystemExit(f'Bad useSpellRef count for {ref}')
ids = re.findall(r'\bid = "([a-z0-9]+)"', items)
if len(ids) != len(set(ids)):
    raise SystemExit('Duplicate item ids detected')
