local function assertEqual(actual, expected, message)
    if actual ~= expected then
        error(("%s: expected %s, got %s"):format(message, tostring(expected), tostring(actual)), 2)
    end
end

local function assertTrue(value, message)
    if value ~= true then error(message, 2) end
end

local Addon = {
    Client = {
        Spellcasting = {
            AuraManager = {
                ResolveEffectAmount = function(_, _, effect, baseField)
                    return tonumber(effect[baseField]) or 0
                end,
            },
        },
    },
    Internal = {
        Database = {
            Dependecies = {},
        },
        Comms = {
            ResourceSync = {},
        },
        Profile = {},
        Registry = {},
    },
    Utils = {
        Common = {
            Round = function(value) return math.floor((tonumber(value) or 0) + 0.5) end,
        },
    },
}

local function loadAddonFile(path)
    local chunk, loadError = loadfile(path)
    assert(chunk, loadError)
    chunk("RPEngine2", Addon)
end

loadAddonFile("client/spellcasting/TooltipTemplate.lua")
loadAddonFile("client/spellcasting/AuraDescriptionBuilder.lua")

local aura = {
    effects = {
        {
            baseAmount = 30,
            operation = "percent",
            statRef = "Threat",
            type = "stat",
        },
    },
}
local payload = {
    bodyText = "Increases Threat Generated by {AURA_STAT_1}%.",
    bodyTokens = {
        {
            applyMode = "stat_amount",
            baseField = "baseAmount",
            effectIndex = 1,
            key = "AURA_STAT_1",
            tokenType = "aura_amount",
        },
    },
    stackingText = "",
    stackingTokens = {},
}

local rendered, renderError = Addon.Client.Spellcasting.AuraDescriptionBuilder:ResolveTooltipTemplatePayload(aura, payload, {})
assertTrue(rendered ~= nil, renderError or "Aura tooltip rendering failed")
assertEqual(rendered, "Increases Threat Generated by 30%.", "percentage aura token rendering")
local _, percentCount = rendered:gsub("%%", "")
assertEqual(percentCount, 1, "percentage aura token does not duplicate percent signs")

print("TooltipBuilderRegressionTest passed")
