local _, Addon = ...

Addon.Internal = Addon.Internal or {}
Addon.Internal.Ruleset = Addon.Internal.Ruleset or {}
Addon.Internal.Ruleset.Rules = Addon.Internal.Ruleset.Rules or {}

local Rules = Addon.Internal.Ruleset.Rules

Rules.Definitions = {
    {
        key = "setup",
        label = "Setup Wizard",
        rules = {
            { key = "enable_setup_wizard", label = "Enable Setup Wizard", type = "checkbox", default = false, description = "Allow the profile setup wizard and apply its ruleset-driven filters." },
            { key = "forced_dataset_ids", label = "Forced Datasets", type = "dropdown", default = {}, multiSelect = true, description = "Datasets that should be activated when the setup wizard is opened.", optionsSource = "datasetId" },
            { key = "force_deactivate_other_datasets", label = "Force Deactivate Other Datasets", type = "checkbox", default = false, description = "Deactivate datasets not included in the forced list when the setup wizard is opened." },
            { key = "allowed_race_refs", label = "Allowed Races", type = "dropdown", default = {}, multiSelect = true, description = "Restrict setup wizard race choices to these race definitions. Leave empty to allow all activated races.", optionsSource = "raceReference" },
            { key = "allowed_class_refs", label = "Allowed Classes", type = "dropdown", default = {}, multiSelect = true, description = "Restrict setup wizard class choices to these class definitions. Leave empty to allow all activated classes.", optionsSource = "classReference" },
            { key = "starting_item_tags", label = "Starting Item Tags", type = "text", default = "", description = "Comma-separated item tags that qualify items for the setup wizard starting-item picker." },
            { key = "starting_item_budget_copper", label = "Starting Item Budget (Copper)", type = "text", default = "0", description = "Optional copper budget for the setup wizard starting-item picker. Use 0 to disable the budget." },
            { key = "required_starting_item_slot_refs", label = "Required Starting Item Slots", type = "dropdown", default = {}, multiSelect = true, description = "Require the setup wizard selection to include equipable items that satisfy these item slots.", optionsSource = "itemSlotReference" },
        },
    },
    {
        key = "character",
        label = "Character",
        rules = {
            { key = "use_level_system", label = "Use Level System", type = "checkbox", default = false, description = "Enable character level progression logic." },
            { key = "starting_level", label = "Starting Level", type = "text", default = "1", description = "Default starting level for new characters." },
            { key = "use_races", label = "Use Races", type = "checkbox", default = false, description = "Enable race-based stat and resource base progression." },
            { key = "use_classes", label = "Use Classes", type = "checkbox", default = false, description = "Enable class-based stat and resource base progression." },
        },
    },
    {
        key = "resources",
        label = "Resources",
        rules = {
            { key = "health_stat", label = "Health Resource", type = "dropdown", default = "", description = "Select the resource reference used for maximum health calculations.", optionsSource = "resourceReference" },
            { key = "use_base_resource_fallback", label = "Use Base Resource Fallback", type = "checkbox", default = true, description = "Use a fallback fraction of resolved max resource when race/class data does not define a base resource." },
            { key = "base_resource_fallback", label = "Base Resource Fallback", type = "text", default = "1.0", description = "Fallback fraction from 0 to 1 used to derive base resources from resolved max values." },
            { key = "enable_resource_regeneration_per_turn", label = "Enable Resource Regeneration Per Turn", type = "checkbox", default = true, description = "Automatically apply configured resource regeneration when an eligible unit's turn begins." },
        },
    },
    {
        key = "combat",
        label = "Combat",
        rules = {
            { key = "block_chance_stat", label = "Block Chance Stat", type = "dropdown", default = "", description = "Select the stat reference used for block chance.", optionsSource = "statReference" },
            { key = "allow_block_without_shield", label = "Allow Block Without Shield", type = "checkbox", default = true, description = "Allow the block reaction tied to the block chance stat even when the defender has no shield equipped." },
            {
                key = "defence_system",
                label = "Defence System",
                type = "dropdown",
                default = "ac",
                description = "Select how hit checks are resolved for player defenders.",
                options = {
                    { label = "Armor Class", value = "ac" },
                    { label = "Simple", value = "simple" },
                    { label = "Complex", value = "complex" },
                    { label = "Percent", value = "percent" },
                },
            },
            { key = "armor_class_stat", label = "Armor Class Stat", type = "dropdown", default = "", description = "Select the stat reference used for armor class checks.", optionsSource = "statReference" },
            { key = "simple_attack_stat", label = "Simple Attack Stat", type = "dropdown", default = "", description = "Select the stat reference added to non-percent attack totals.", optionsSource = "statReference" },
            { key = "simple_defence_stat", label = "Simple Defence Stat", type = "dropdown", default = "", description = "Select the stat reference added to simple defence rolls.", optionsSource = "statReference" },
            { key = "complex_defence_stats_melee", label = "Complex Melee Defences", type = "dropdown", default = {}, multiSelect = true, description = "Select the defence stats available against melee attacks.", optionsSource = "statReference" },
            { key = "complex_defence_stats_ranged", label = "Complex Ranged Defences", type = "dropdown", default = {}, multiSelect = true, description = "Select the defence stats available against ranged attacks.", optionsSource = "statReference" },
            { key = "complex_defence_stats_spell", label = "Complex Spell Defences", type = "dropdown", default = {}, multiSelect = true, description = "Select the defence stats available against spell attacks.", optionsSource = "statReference" },
            { key = "percent_melee_hit_stat", label = "Percent Melee Hit Stat", type = "dropdown", default = "", description = "Select the hit stat used for percent melee checks.", optionsSource = "statReference" },
            { key = "percent_ranged_hit_stat", label = "Percent Ranged Hit Stat", type = "dropdown", default = "", description = "Select the hit stat used for percent ranged checks.", optionsSource = "statReference" },
            { key = "percent_spell_hit_stat", label = "Percent Spell Hit Stat", type = "dropdown", default = "", description = "Select the hit stat used for percent spell checks.", optionsSource = "statReference" },
            { key = "percent_melee_resistance_stat", label = "Percent Melee Resistance Stats", type = "dropdown", default = {}, multiSelect = true, description = "Select the resistance stats summed against percent melee checks.", optionsSource = "statReference" },
            { key = "percent_ranged_resistance_stat", label = "Percent Ranged Resistance Stats", type = "dropdown", default = {}, multiSelect = true, description = "Select the resistance stats summed against percent ranged checks.", optionsSource = "statReference" },
            { key = "percent_spell_resistance_stat", label = "Percent Spell Resistance Stats", type = "dropdown", default = {}, multiSelect = true, description = "Select the resistance stats summed against percent spell checks.", optionsSource = "statReference" },
            {
                key = "limit_defensive_reactions_per_turn",
                label = "Limit Defensive Reactions Per Turn",
                type = "checkbox",
                default = false,
                description = "When enabled, each defensive reaction/stat may be used once per Event turn unless it is configured to bypass the limit.",
            },
            {
                key = "defensive_reaction_limit_bypass_stats",
                label = "Unlimited Defensive Reactions",
                type = "dropdown",
                default = {},
                multiSelect = true,
                optionsSource = "statReference",
                description = "Defensive stats that remain usable without limit when the per-turn defensive reaction limit is enabled.",
            },
            { key = "attack_roll_dice", label = "Attack Roll Dice", type = "text", default = "1d20", description = "Dice expression used for non-percent attacker rolls." },
            { key = "defence_roll_dice", label = "Defence Roll Dice", type = "text", default = "1d20", description = "Dice expression used for defender rolls." },
            { key = "percent_base_penalty", label = "Percent Base Penalty", type = "text", default = "0", description = "Fixed value subtracted from the 1-100 attack roll in percent mode." },
            {
                key = "damage_school_mitigation_model",
                label = "Damage School Mitigation Model",
                type = "dropdown",
                default = "legacy",
                description = "Choose how damage-school mitigation stats convert into applied mitigation.",
                options = {
                    { label = "Legacy", value = "legacy" },
                    { label = "Fixed Percent", value = "fixed_percent" },
                    { label = "Level Scaled Percent", value = "level_scaled_percent" },
                },
            },
            { key = "damage_school_mitigation_reference_level", label = "Damage School Mitigation Reference Level", type = "text", default = "60", description = "Reference level used when level-scaled mitigation is enabled." },
            { key = "critical_damage_mitigation_stat", label = "Critical Damage Mitigation Stat", type = "dropdown", default = "", description = "Select the stat reference used to mitigate critical and crushing damage taken.", optionsSource = "statReference" },
            { key = "critical_damage_mitigation_mode", label = "Critical Damage Mitigation Mode", type = "dropdown", default = "direct", description = "Choose whether critical-damage mitigation applies as direct damage reduction or percent reduction in legacy mode.", options = {
                { label = "Direct", value = "direct" },
                { label = "Percent", value = "percent" },
            } },
            { key = "critical_damage_mitigation_coefficient", label = "Critical Damage Mitigation Coefficient", type = "text", default = "1", description = "Coefficient applied to the critical-damage mitigation stat in legacy mode." },
            {
                key = "critical_damage_mitigation_model",
                label = "Critical Damage Mitigation Model",
                type = "dropdown",
                default = "legacy",
                description = "Choose how the critical-damage mitigation stat converts into applied mitigation.",
                options = {
                    { label = "Legacy", value = "legacy" },
                    { label = "Fixed Percent", value = "fixed_percent" },
                    { label = "Level Scaled Percent", value = "level_scaled_percent" },
                },
            },
            { key = "critical_damage_mitigation_reference_amount", label = "Critical Damage Mitigation Amount", type = "text", default = "0", description = "Stat amount used as the reference point for crit mitigation in fixed-percent and level-scaled modes." },
            { key = "critical_damage_mitigation_reference_percent", label = "Critical Damage Mitigation Percent", type = "text", default = "0", description = "Percent mitigation granted at the reference amount in fixed-percent and level-scaled modes." },
            { key = "critical_damage_mitigation_reference_level", label = "Critical Damage Mitigation Reference Level", type = "text", default = "60", description = "Reference level used when crit mitigation level scaling is enabled." },
            { key = "damage_dealt_stat", label = "Damage Dealt Stat", type = "dropdown", default = "", description = "Select the stat reference used for final damage dealt modifiers.", optionsSource = "statReference" },
            { key = "spell_damage_vs_aberration_stat", label = "Spell Damage vs Aberration Stat", type = "dropdown", default = "", description = "Select the stat reference used for bonus spell damage against aberration targets.", optionsSource = "statReference" },
            { key = "spell_damage_vs_beast_stat", label = "Spell Damage vs Beast Stat", type = "dropdown", default = "", description = "Select the stat reference used for bonus spell damage against beast targets.", optionsSource = "statReference" },
            { key = "spell_damage_vs_demon_stat", label = "Spell Damage vs Demon Stat", type = "dropdown", default = "", description = "Select the stat reference used for bonus spell damage against demon targets.", optionsSource = "statReference" },
            { key = "spell_damage_vs_dragonkin_stat", label = "Spell Damage vs Dragonkin Stat", type = "dropdown", default = "", description = "Select the stat reference used for bonus spell damage against dragonkin targets.", optionsSource = "statReference" },
            { key = "spell_damage_vs_elemental_stat", label = "Spell Damage vs Elemental Stat", type = "dropdown", default = "", description = "Select the stat reference used for bonus spell damage against elemental targets.", optionsSource = "statReference" },
            { key = "spell_damage_vs_giant_stat", label = "Spell Damage vs Giant Stat", type = "dropdown", default = "", description = "Select the stat reference used for bonus spell damage against giant targets.", optionsSource = "statReference" },
            { key = "spell_damage_vs_humanoid_stat", label = "Spell Damage vs Humanoid Stat", type = "dropdown", default = "", description = "Select the stat reference used for bonus spell damage against humanoid targets.", optionsSource = "statReference" },
            { key = "spell_damage_vs_mechanical_stat", label = "Spell Damage vs Mechanical Stat", type = "dropdown", default = "", description = "Select the stat reference used for bonus spell damage against mechanical targets.", optionsSource = "statReference" },
            { key = "spell_damage_vs_undead_stat", label = "Spell Damage vs Undead Stat", type = "dropdown", default = "", description = "Select the stat reference used for bonus spell damage against undead targets.", optionsSource = "statReference" },
            { key = "damage_reduction_stat", label = "Damage Reduction Stat", type = "dropdown", default = "", description = "Select the stat reference used for final damage reduction modifiers.", optionsSource = "statReference" },
            { key = "healing_done_stat", label = "Healing Done Stat", type = "dropdown", default = "", description = "Select the stat reference used for final healing done modifiers.", optionsSource = "statReference" },
            { key = "healing_received_stat", label = "Healing Received Stat", type = "dropdown", default = "", description = "Select the stat reference used for final healing received modifiers.", optionsSource = "statReference" },
            { key = "threat_generated_stat", label = "Threat Generated Stat", type = "dropdown", default = "", description = "Select the stat reference used for final threat generated modifiers.", optionsSource = "statReference" },
            { key = "base_melee_crit_chance", label = "Base Melee Crit Chance", type = "text", default = "0", description = "Base melee critical-strike chance percent." },
            { key = "base_ranged_crit_chance", label = "Base Ranged Crit Chance", type = "text", default = "0", description = "Base ranged critical-strike chance percent." },
            { key = "base_spell_crit_chance", label = "Base Spell Crit Chance", type = "text", default = "0", description = "Base spell critical-strike chance percent." },
            { key = "base_healing_crit_chance", label = "Base Healing Crit Chance", type = "text", default = "0", description = "Base healing critical-strike chance percent." },
            { key = "percent_melee_crit_stat", label = "Percent Melee Crit Stat", type = "dropdown", default = "", description = "Select the melee crit stat used in percent mode.", optionsSource = "statReference" },
            { key = "percent_ranged_crit_stat", label = "Percent Ranged Crit Stat", type = "dropdown", default = "", description = "Select the ranged crit stat used in percent mode.", optionsSource = "statReference" },
            { key = "percent_spell_crit_stat", label = "Percent Spell Crit Stat", type = "dropdown", default = "", description = "Select the spell crit stat used in percent mode.", optionsSource = "statReference" },
            { key = "percent_healing_crit_stat", label = "Percent Healing Crit Stat", type = "dropdown", default = "", description = "Select the healing crit stat used in percent mode.", optionsSource = "statReference" },
            { key = "simple_melee_crit_stat", label = "Simple Melee Crit Stat", type = "dropdown", default = "", description = "Select the melee crit stat used in AC and simple mode.", optionsSource = "statReference" },
            { key = "simple_ranged_crit_stat", label = "Simple Ranged Crit Stat", type = "dropdown", default = "", description = "Select the ranged crit stat used in AC and simple mode.", optionsSource = "statReference" },
            { key = "simple_spell_crit_stat", label = "Simple Spell Crit Stat", type = "dropdown", default = "", description = "Select the spell crit stat used in AC and simple mode.", optionsSource = "statReference" },
            { key = "simple_healing_crit_stat", label = "Simple Healing Crit Stat", type = "dropdown", default = "", description = "Select the healing crit stat used in AC and simple mode.", optionsSource = "statReference" },
            { key = "complex_melee_crit_stat", label = "Complex Melee Crit Stat", type = "dropdown", default = "", description = "Select the melee crit stat used in complex mode.", optionsSource = "statReference" },
            { key = "complex_ranged_crit_stat", label = "Complex Ranged Crit Stat", type = "dropdown", default = "", description = "Select the ranged crit stat used in complex mode.", optionsSource = "statReference" },
            { key = "complex_spell_crit_stat", label = "Complex Spell Crit Stat", type = "dropdown", default = "", description = "Select the spell crit stat used in complex mode.", optionsSource = "statReference" },
            { key = "complex_healing_crit_stat", label = "Complex Healing Crit Stat", type = "dropdown", default = "", description = "Select the healing crit stat used in complex mode.", optionsSource = "statReference" },
            { key = "critical_roll_dice", label = "Critical Roll Dice", type = "text", default = "1d20", description = "Dice expression used for non-percent critical checks." },
            { key = "critical_damage_multiplier", label = "Critical Damage Multiplier", type = "text", default = "2.0", description = "Multiplier applied before mitigation for critical damage results." },
            { key = "critical_healing_multiplier", label = "Critical Healing Multiplier", type = "text", default = "2.0", description = "Multiplier applied before resource application for critical heals." },
            { key = "crushing_blow_damage_multiplier", label = "Crushing Blow Damage Multiplier", type = "text", default = "1.5", description = "Multiplier applied before mitigation for crushing blows." },
        },
    },
    {
        key = "weapon_combat",
        label = "Weapon Combat",
        rules = {
            { key = "skill_based_hit_chance", label = "Skill Based Hit Chance", type = "checkbox", default = false, description = "Apply event-level weapon skill deficits as hit penalties for weapon damage." },
            { key = "weapon_skill_hit_modifier_per_point", label = "Weapon Skill Hit Modifier Per Point", type = "text", default = "1", description = "Percent hit penalty applied per point below the expected weapon skill." },
            { key = "weapon_skill_hit_modifier_cap", label = "Weapon Skill Hit Modifier Cap", type = "text", default = "25", description = "Maximum percent hit penalty applied from weapon skill deficits." },
            { key = "enable_crushing_blows", label = "Enable Crushing Blows", type = "checkbox", default = false, description = "Allow event-level weapon skill surpluses to influence crushing and critical weapon hits." },
            { key = "weapon_skill_crit_modifier_per_point", label = "Weapon Skill Crit Modifier Per Point", type = "text", default = "1", description = "Percent crit bonus applied per point above the expected weapon skill." },
            { key = "weapon_skill_crit_modifier_cap", label = "Weapon Skill Crit Modifier Cap", type = "text", default = "25", description = "Maximum percent crit bonus applied from weapon skill surpluses." },
        },
    },
    {
        key = "event",
        label = "Event",
        rules = {
            { key = "max_event_units", label = "Max Event Units", type = "text", default = "5", description = "Maximum number of event units shown per turn page." },
            { key = "event_end_justice_currency", label = "End Event Justice", type = "text", default = "100", description = "Justice granted automatically to each participant when an event ends. Set to 0 to disable." },
            { key = "boss_kill_valor_currency", label = "Boss Kill Valor", type = "text", default = "25", description = "Valor granted automatically to each participant when a boss-flag NPC dies. Set to 0 to disable." },
            { key = "initiative_stat", label = "Initiative Stat", type = "dropdown", default = "", description = "Select the stat reference used to resolve initiative.", optionsSource = "statReference", retainedWithoutConsumer = true },
            {
                key = "allowed_event_difficulties",
                label = "Allowed Event Difficulties",
                type = "dropdown",
                default = { "normal", "heroic", "mythic" },
                multiSelect = true,
                description = "Choose which event difficulty modes can be selected in the event manager.",
                options = {
                    { label = "Normal", value = "normal" },
                    { label = "Heroic", value = "heroic" },
                    { label = "Mythic", value = "mythic" },
                },
            },
        },
    },
    {
        key = "equipment",
        label = "Equipment",
        rules = {
            { key = "mainhand_slot", label = "Main Hand Slot", type = "dropdown", default = "", description = "Select the item slot reference used for the unit main-hand assignment.", optionsSource = "itemSlotReference" },
            { key = "offhand_slot", label = "Off Hand Slot", type = "dropdown", default = "", description = "Select the item slot reference used for the unit off-hand assignment.", optionsSource = "itemSlotReference" },
            { key = "ranged_slot", label = "Ranged Slot", type = "dropdown", default = "", description = "Select the item slot reference used for the unit ranged assignment.", optionsSource = "itemSlotReference" },
            { key = "shield_slot", label = "Shield Slot", type = "dropdown", default = "", description = "Select the item slot reference used for the unit shield assignment.", optionsSource = "itemSlotReference" },
            { key = "allow_dual_wield", label = "Allow Dual Wield", type = "checkbox", default = false, description = "Enable dual-wield logic for weapon handling.", retainedWithoutConsumer = true },
        },
    },
    {
        key = "traits",
        label = "Traits",
        rules = {
            { key = "max_total_traits", label = "Max Total Traits", type = "text", default = "0", description = "Maximum number of manually learned traits allowed. Use 0 for unlimited." },
            { key = "base_talent_traits", label = "Base Talent Traits", type = "text", default = "999", description = "Number of manual talent traits allowed before level scaling is added." },
            { key = "talent_traits_per_level", label = "Talent Traits Per Level", type = "text", default = "0", description = "Additional manual talent traits granted per level above 1." },
            { key = "auto_enable_race_traits", label = "Auto Enable Race Traits", type = "checkbox", default = true, description = "Automatically activate traits assigned to the selected race." },
            { key = "auto_enable_class_traits", label = "Auto Enable Class Traits", type = "checkbox", default = true, description = "Automatically activate traits assigned to the selected class." },
            { key = "count_race_traits_toward_total", label = "Count Race Traits Toward Total", type = "checkbox", default = false, description = "Count auto-enabled race traits against the total-trait cap." },
            { key = "count_class_traits_toward_total", label = "Count Class Traits Toward Total", type = "checkbox", default = false, description = "Count auto-enabled class traits against the total-trait cap." },
            { key = "allow_class_traits", label = "Allow Class Traits", type = "checkbox", default = true, description = "Allow learned class traits to affect the character and appear in trait views." },
            { key = "allow_race_traits", label = "Allow Race Traits", type = "checkbox", default = true, description = "Allow learned racial traits to affect the character and appear in trait views." },
        },
    },
    {
        key = "consumables",
        label = "Consumables",
        rules = {
            { key = "allow_consumable_traits", label = "Allow Consumable Traits", type = "checkbox", default = true, description = "Allow consumable-item traits to appear in trait views and trigger phase prompts." },
            { key = "required_consumable_item_tags", label = "Required Consumable Item Tags", type = "text", default = "", description = "Comma-separated tag whitelist for consumable traits. Items must match at least one required tag when any are configured." },
            { key = "flask_limit", label = "Flask Limit", type = "text", default = "1", description = "Maximum number of flask consumables that can be selected at once. Use 0 for unlimited." },
            { key = "scroll_limit", label = "Scroll Limit", type = "text", default = "1", description = "Maximum number of scroll consumables that can be selected at once. Use 0 for unlimited." },
            { key = "rune_limit", label = "Rune Limit", type = "text", default = "1", description = "Maximum number of rune consumables that can be selected at once. Use 0 for unlimited." },
            { key = "elixir_limit", label = "Elixir Limit", type = "text", default = "0", description = "Maximum number of elixir consumables that can be selected when categorisation is disabled. Use 0 for unlimited." },
            { key = "elixir_categorisation", label = "Elixir Categorisation", type = "checkbox", default = false, description = "Require elixir consumables to use battle or guardian tags, cap elixirs at 2, and allow at most one battle and one guardian elixir." },
        },
    },
    {
        key = "skills",
        label = "Skills",
        rules = {
            { key = "use_weapon_skills", label = "Use Weapon Skills", type = "checkbox", default = true, description = "Enable weapon skills in skill resolution and profile views." },
            { key = "use_noncombat_skills", label = "Use Non-Combat Skills", type = "checkbox", default = true, description = "Enable non-combat skills in skill resolution and profile views." },
            { key = "use_crafting_skills", label = "Use Crafting Skills", type = "checkbox", default = true, description = "Enable crafting skills in skill resolution and profile views." },
            { key = "use_language_skills", label = "Use Language Skills", type = "checkbox", default = true, description = "Enable language skills in skill resolution and profile views." },
            { key = "weapon_skill_level_multiplier", label = "Weapon Skill Level Multiplier", type = "text", default = "5", description = "Multiplier used to derive weapon skill caps from the profile level." },
            { key = "noncombat_skill_max_level", label = "Non-Combat Skill Max Level", type = "text", default = "100", description = "Maximum resolved level shown for non-combat skills." },
            { key = "crafting_skill_max_level", label = "Crafting Skill Max Level", type = "text", default = "100", description = "Maximum resolved level shown for crafting skills." },
            { key = "language_skill_max_level", label = "Language Skill Max Level", type = "text", default = "100", description = "Maximum resolved level shown for language skills." },
            { key = "allow_permanent_skill_bonuses_after_setup", label = "Allow Permanent Skill Bonuses After Setup", type = "checkbox", default = false, description = "Allow players to manually add permanent skill bonuses from the Skills window after character setup." },
            { key = "weapon_skill_gain_chance_on_hit", label = "Weapon Skill Gain Chance On Hit", type = "text", default = "0", description = "Percent chance to gain weapon skill progression from a valid hit." },
            { key = "noncombat_skill_gain_chance_on_roll", label = "Non-Combat Skill Gain Chance On Roll", type = "text", default = "0", description = "Percent chance to gain non-combat skill progression from a valid roll." },
            { key = "language_skill_gain_chance", label = "Language Skill Gain Chance", type = "text", default = "0", description = "Percent chance to gain language skill progression from supported language actions." },
        },
    },
    {
        key = "mounts",
        label = "Mounts",
        rules = {
            { key = "dismount_resistance_stat", label = "Dismount Resistance Stat", type = "dropdown", default = "", description = "Select the stat reference used for dismount resistance checks.", optionsSource = "statReference" },
            { key = "dismount_on_direct_damage", label = "Dismount On Direct Damage", type = "checkbox", default = false, description = "Allow positive direct-damage hits against the mounted local player to trigger a dismount check." },
            { key = "allow_mount_in_combat", label = "Allow Mount In Combat", type = "checkbox", default = false, description = "Allow the local player to mount while participating in an active event." },
            { key = "movement_range_stat", label = "Movement Range Stat", type = "dropdown", default = "", description = "Select the stat reference used for movement range while in events.", optionsSource = "statReference" },
        },
    },
    {
        key = "interface",
        label = "Interface",
        rules = {
            { key = "action_bar_size", label = "Action Bar Size", type = "text", default = "5", description = "Number of spell slots shown in the player action bar widget." },
            { key = "use_item_level", label = "Use Item Level", type = "checkbox", default = true, description = "Show item level in eligible item tooltips and the profile equipment summary." },
            {
                key = "trait_display_mode",
                label = "Trait Display Mode",
                type = "dropdown",
                default = "grouped",
                description = "Choose whether the profile trait page groups traits by category or shows them together.",
                options = {
                    { label = "Grouped", value = "grouped" },
                    { label = "Flat", value = "flat" },
                },
            },
            { key = "mounted_action_bar", label = "Mounted Action Bar", type = "checkbox", default = false, description = "Swap to a dedicated mounted spell bar while mounted." },
            { key = "mounted_action_bar_only_mounted_combat_spells", label = "Mounted Bar Only Mounted Combat Spells", type = "checkbox", default = false, description = "Restrict mounted bar bindings to spells flagged as mounted combat only." },
        },
    },
}
