local _, Addon = ...

local UI = Addon.UI or {}
Addon.UI = UI

UI.Constants = UI.Constants or {
    Layout = {
        RootSpacing = 10,
        SectionSpacing = 8,
        ToolbarSpacing = 0,
        ContentPadding = 16,
        RowSpacing = 0,
        DemoSectionSpacing = 10,
    },
    FontSizes = {
        WindowTitle = 8,
        Heading1 = 12,
        Heading2 = 10,
        Body = 8,
        Small = 6,
        ButtonLabel = 8,
        Checkbox = 8,
        Dropdown = 8,
        DropdownArrow = 10,
        PaginatedNav = 8,
        PaginatedPage = 8,
        ProgressBar = 6,
        SliderBar = 10,
        ScrollCategory = 8,
        ScrollName = 8,
        ScrollStatus = 8,
        ScrollDetail = 8,
        TabLabel = 8,
    },
    FontFiles = {
        Default = "Fonts\\FRIZQT__.TTF",
    },
    FontObjects = {
        WindowTitle = "GameFontNormal",
        Heading1 = "GameFontHighlightSmall",
        Heading2 = "GameFontHighlightSmall",
        Body = "GameFontNormalSmall",
        Small = "GameFontNormalSmall",
        Text = "GameFontNormalSmall",
        TextButton = "GameFontNormal",
        Checkbox = "GameFontNormal",
        Dropdown = "GameFontNormal",
        DropdownArrow = "GameFontNormalSmall",
        PaginatedNav = "GameFontNormal",
        PaginatedPage = "GameFontHighlightSmall",
        ProgressBar = "GameFontNormalSmall",
        SliderBar = "GameFontNormalSmall",
        ScrollCategory = "GameFontNormalSmall",
        ScrollName = "GameFontNormalSmall",
        ScrollStatus = "GameFontHighlightSmall",
        ScrollDetail = "GameFontDisableSmall",
        TabLabel = "GameFontHighlightSmall",
        ButtonLabel = "GameFontNormal",
    },
    Heights = {
        WindowHeader = 16,
        IntroPanel = 44,
        VisualsPanel = 72,
        ControlsPanel = 116,
        PaginationPanel = 96,
        ScrollPanel = 124,
        ProgressBar = 12,
        ProgressControl = 12,
        SliderControl = 12,
    },
    Scroll = {
        DefaultVisibleRows = 8,
        DefaultRowHeight = 24,
        RowSpacing = 2,
        RegisteredTestsVisibleRows = 30,
        DemoVisibleRows = 7,
        DemoRowHeight = 24,
        RegisteredRowHeight = 16,
    },
    Window = {
        TitleOffsetY = 16,
        ContentInsetLeft = 8,
        ContentInsetRight = 8,
        ContentInsetTop = 20,
        ContentInsetBottom = 8,
        BorderSize = 2,
    },
    Prefabs = {
        UnitPortrait = {
            PortraitSize = 32,
            PortraitBorderSize = 2,
            ProgressHeight = 4,
            ProgressSpacing = 4,
            MinValue = 0,
            MaxValue = 100,
            Value = 72,
            Unit = "player",
            PortraitTexture = "Interface\\Icons\\INV_Misc_QuestionMark",
            PortraitTexCoord = { left = 0, right = 1, top = 0, bottom = 1 },
            PortraitBorderColor = { r = 0.85, g = 0.24, b = 0.24, a = 1 },
            ProgressBackgroundColor = { r = 0.08, g = 0.09, b = 0.12, a = 1 },
            ProgressBorderColor = { r = 0.16, g = 0.18, b = 0.22, a = 1 },
            ProgressPrimaryColor = { r = 0.42, g = 0.66, b = 0.98, a = 1 },
            ProgressSecondaryColor = { r = 0.25, g = 0.42, b = 0.68, a = 1 },
            ProgressTextColor = { r = 1, g = 1, b = 1, a = 1 },
        },
        ObjectSlot = {
            Size = 36,
            BorderSize = 2,
            IconTexture = "Interface\\Icons\\INV_Misc_QuestionMark",
            IconTexCoord = { left = 0.03, right = 0.97, top = 0.03, bottom = 0.97 },
            CountInsetX = 3,
            CountInsetY = 3,
            CountFontSize = 10,
            OverlayFontSize = 12,
            BorderColor = { r = 0.42, g = 0.46, b = 0.52, a = 1 },
            BackgroundColor = { r = 0.07, g = 0.08, b = 0.1, a = 0.95 },
        },
        ResourceBar = {
            Width = 220,
            Height = 14,
            IconSize = 14,
            ValueWidth = 44,
            ProgressFontSize = 10,
            ValueFontSize = 10,
            IconTexture = "Interface\\Icons\\INV_Misc_QuestionMark",
        },
        CastBar = {
            Width = 220,
            Height = 14,
            IconSize = 14,
            ValueWidth = 44,
            ProgressFontSize = 12,
            ValueFontSize = 10,
            IconTexture = "Interface\\Icons\\INV_Misc_QuestionMark",
        },
        StatEntry = {
            Width = 180,
            Height = 14,
            IconSize = 8,
            IconTexture = "Interface\\Icons\\INV_Misc_QuestionMark",
            IconToNameSpacing = 6,
            ValueWidth = 52,
            FontSize = 8,
            ValueFontSize = 8,
            StatName = "Statistic",
            StatValue = "0",
        },
    },
}

return UI.Constants
